version: '3'

networks:
  database_default:
    external: true

services:
  main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 9000:8000
        networks:
          - database_default